import type {Metadata} from "next";
import "./globals.css";

import {NextIntlClientProvider} from 'next-intl';
import {getLocale, getMessages} from 'next-intl/server';
import React from "react";
import React19Compatability from "@/app/components/React19Compatability";
import ReactQueryProvider from "@/app/components/ReactQueryProvider";
import {getServerSession} from "next-auth";
import CredentialsProvider from "next-auth/providers/credentials";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
                                           children,
                                         }: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  const locale = await getLocale();

  const messages = await getMessages();


  return (
    <html lang={locale}>
      <body>
      <React19Compatability/>
      <ReactQueryProvider>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </ReactQueryProvider>
      </body>
    </html>
  );
}
